### PR TITLE
Adding example of lamp matrix config

### PR DESCRIPTION
**Pull request by mikelatiolais**
An example for defining the lamp matrix on an xpansion board

### CODE REVIEW

**Comment by cobra18t** [comment]
Can you reference that this is for the Xpansion board either in the title of the file or in the comment text in the file? I don't want people thinking they can do this with the main board.

**Comment by mikelatiolais** [comment]
I added a note in the comments.

**Comment by mikelatiolais** [comment]
I can add more notes if you like. Something along the lines of
# NOTE: This config requires an Xpansion board and will not work with a Cobrapin board alone

**Comment by cobra18t** [comment]
The simple note is fine, I can always edit it if it becomes an issue.

**Pull request merged**
